### ISSUE TITLE
Allow ability to submit form with 'Enter'

### ISSUE THREAD

**Issue by silvaDominic** [semanticdata/firefox-chatgpt-in-sidebar#2]
Doesn't look like there's anyway to use the keyboard to submit the form. Even tabbing to the button and pressing 'Enter' doesn't work.

Is this a limitation?

**Comment by semanticdata** [comment]
Hi @silvaDominic.

Thank you for taking the time to write this. Unfortunately, you are correct in that it is a limitation of the Firefox sidebar. We are only able to redirect it to open their webapp inside of it, and the behaviour of said webapp is not up to us from there on.

**Comment by silvaDominic** [comment]
Got it. Curious if you know specifically why.

I did a cursory search and it seems it could have to do with the host site's handling of events.

**Comment by silvaDominic** [comment]
Accidentally confirmed that the issue has to do with how 'submit' events are handled between mobile and desktop. If you resize the side panel to trigger a tablet or greater view, submit works just like normal. Once you hit the mobile width threshold though, 'submit' is handled differently.

**Comment by semanticdata** [comment]
Thank you for the follow-up. It satisfied my curiosity as well!
